fix: used json.dumps instead of str in sanitize_params
supabase/postgrest-py pull request #161
Opened 2022-10-15 19:58 UTC by aduuna

## What kind of change does this PR introduce?

Bug fix

## What is the current behavior?

#131 Use json.dumps instead of str in sanitize_params

## What is the new behavior?

Feel free to include screenshots if it includes visual changes.

## Additional context

Add any other context or screenshots.

2022-10-21 15:42 UTC, rawandahmad698 commented
looks good.

2022-10-21 15:42 UTC, rawandahmad698 submitted a review, later dismissed

2022-10-26 16:29 UTC, anand2312 requested changes
Tests are failing, please fix them (you added the import statement above the `future` statement which causes a syntax error)

2023-01-23 05:25 UTC, J0 commented
Think we might need to update the test cases for this one as well - would be great if someone can jump on - otherwise I'll take a look when there's a free cycle

2023-02-11 07:53 UTC, J0 commented
Hey,

Going to fix the tests on this one so we can get it in - hope you don't mind!

2024-07-19 10:12 UTC, silentworks commented
This will result in a breaking change at the moment. I've ran the tests and there are too many broken tests to get this into a release.

2025-01-29 10:02 UTC, closed without merging